### ISSUE TITLE
批量删除功能造成了应用闪退

### ISSUE THREAD

**Issue by raoxiongwen** [youniaogu/MangaReader#159]
最新版apk，长按勾选漫画，点击删除ICON，此时应用就会闪退。
奇怪的地方是调试模式下，功能是能够正常运行的，release包运行才会出现问题，下面是我用adb logcat捕获的错误信息
![Snipaste_2024-06-11_14-41-03](https://github.com/youniaogu/MangaReader/assets/75081273/d08ffdf3-610a-48df-891a-32e07578984c)
```js
06-11 14:39:38.922  9108  9108 D AndroidRuntime: Shutting down VM
06-11 14:39:38.923  9108  9108 E AndroidRuntime: FATAL EXCEPTION: main
06-11 14:39:38.923  9108  9108 E AndroidRuntime: Process: com.youniaogu.mangareader, PID: 9108
06-11 14:39:38.923  9108  9108 E AndroidRuntime: java.lang.IllegalStateException: java.lang.NoSuchFieldException: stroke
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.b0.b0(Unknown Source:93)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.l.i0(Unknown Source:52)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.l.L(Unknown Source:6)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.b0.U(Unknown Source:265)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.g0.N(Unknown Source:158)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.g0.O(Unknown Source:71)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.horcrux.svg.g0.onDraw(Unknown Source:16)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:20221)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19096)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.drawChild(Unknown Source:19)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.dispatchDraw(Unknown Source:3)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:20224)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19096)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.drawChild(Unknown Source:19)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.dispatchDraw(Unknown Source:3)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:20224)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19096)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.drawChild(Unknown Source:19)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.dispatchDraw(Unknown Source:3)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19087)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.drawChild(Unknown Source:19)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.dispatchDraw(Unknown Source:3)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19087)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.drawChild(Unknown Source:19)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.facebook.react.views.view.m.dispatchDraw(Unknown Source:3)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19087)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19087)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19087)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19087)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:19949)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.drawChild(ViewGroup.java:4365)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4144)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.draw(View.java:20224)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:19096)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3318)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3122)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2481)
06-11 14:39:38.923  9108  9108 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1463)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7190)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:696)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6840)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
06-11 14:39:38.924  9108  9108 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: stroke
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at java.lang.Class.getField(Class.java:1601)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        at com.horcrux.svg.b0.b0(Unknown Source:56)
06-11 14:39:38.924  9108  9108 E AndroidRuntime:        ... 77 more
06-11 14:39:38.929  1579  1579 I Thread-48: type=1400 audit(0.0:2033): avc: denied { write } for name="qmux_bluetooth" dev="tmpfs" ino=7554 scontext=u:r:system_server:s0 tcontext=u:object_r:socket_device:s0 tclass=sock_file permissive=1
06-11 14:39:38.940  1579  2179 W ActivityManager:   Force finishing activity com.youniaogu.mangareader/com.mangareader.MainActivity
06-11 14:39:38.929  1579  1579 W Thread-48: type=1300 audit(0.0:2033): arch=c000003e syscall=44 success=yes exit=5193 a0=10d a1=7fff4b13f800 a2=1449 a3=0 items=0 ppid=1402 auid=4294967295 uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 exe="/system/bin/app_process64" subj=u:r:system_server:s0 key=(null)
06-11 14:39:38.955  9108  9108 W System.err: java.lang.Exception: call killProcess callstack! pid=9108
```

**Comment by youniaogu** [comment]
更新了安装包

**Comment by raoxiongwen** [comment]
> 更新了安装包

哈哈哈哈，是因为代码错误导致的吗

**Comment by youniaogu** [comment]
native-base 有 bug，那个 `Modal.CloseButton` 打包之后一渲染就崩，所以我就把那段代码删掉了

https://github.com/youniaogu/MangaReader/commit/730a40a16da90da526f9e01528689efc6caeeed2?diff=unified&w=0#diff-0bd464931de0b56bfdc6ff55c67ed3c4f4d793f4da55bc994791b82f7daad4cbL156

**Comment by raoxiongwen** [comment]
> native-base 有 bug，那个 `Modal.CloseButton` 打包之后一渲染就崩，所以我就把那段代码删掉了
> 
> https://github.com/youniaogu/MangaReader/commit/730a40a16da90da526f9e01528689efc6caeeed2?diff=unified&w=0#diff-0bd464931de0b56bfdc6ff55c67ed3c4f4d793f4da55bc994791b82f7daad4cbL156

学到了，我定位了好久，都找不到问题😭😭
